### PR TITLE
fix: using base-href with ssg was breaking build

### LINKED ISSUE #263: [Bug] When building with prerendering enabled and base href specified builder throws errors
### Is this a regression?

Yes

### Description

When I build ng-doc app with prerendering enabled, and I specify --base-href, then builder throws errors about ui-kit icons:

It can be reproduced by ng-doc demo app in this repository by building with `nx build ng-doc -- --base-href=/test/test2/ --verbose`

### Please provide the exception or error you saw

```true
Wt {
  headers: e {
    headers: Map(0) {},
    normalizedNames: Map(0) {},
    lazyInit: undefined,
    lazyUpdate: null
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'http://ng-localhost/test/test2/assets/ng-doc/ui-kit/icons/16/search.svg#search',
  ok: false,
  type: undefined,
  name: 'HttpErrorResponse',
  message: 'Http failure response for http://ng-localhost/test/test2/assets/ng-doc/ui-kit/icons/16/search.svg#search: 0 undefined',
  error: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11731:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: Error: getaddrinfo ENOTFOUND ng-localhost
        at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
        at __node_internal_ (node:internal/errors:715:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'ng-localhost'
    }
  }
}
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

Checked with 18.19.1 and 20.14.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrianKokot**
Fixes #263

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number

Issue Number: #263 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/app/providers/ng-doc-app/provide-ng-doc-app.ts [hunk 1]
```diff
@@ -35,6 +42,13 @@ export function provideNgDocApp(
       await inject(NgDocHighlighterService).initialize(config?.shiki);
     }),
 
+    {
+      provide: NG_REQUEST_BASE_PATH,
+      useFactory: () => {
```
Comment (skoropadas) [inline libs/app/providers/ng-doc-app/provide-ng-doc-app.ts:47]: I would maybe make it a part of `NG_REQUEST_BASE_PATH` token just to not provide it
something like this
```ts
export const NG_REQUEST_BASE_PATH: InjectionToken<string> = new InjectionToken(
  'NG_REQUEST_BASE_PATH',
  {
    providedIn: 'root',
    factory: () => isPlatformBrowser(inject(PLATFORM_ID)) ? '' : '/'
  }
);
```

**Review by skoropadas — CHANGES_REQUESTED** [review]

File: libs/app/providers/ng-doc-app/provide-ng-doc-app.ts (hunk 1 above)
Comment (AdrianKokot) [reply libs/app/providers/ng-doc-app/provide-ng-doc-app.ts]: done!

**Review by skoropadas — APPROVED** [review]
Awesome! Thanks!
